const categories = [
  "Artist",
  "⁠Accountant",
  "⁠Actor/Actress",
  "⁠Architect",
  "⁠Astronomer",
  "⁠Baker",
  "⁠Biologist",
  "⁠Carpenter",
  "⁠Chef",
  "⁠Chemist",
  "⁠Civil Engineer",
  "⁠Computer Programmer",
  "⁠Counselor",
  "⁠Dancer",
  "⁠Dentist",
  "⁠Detective",
  "⁠Dietitian",
  "⁠Doctor",
  "⁠Economist",
  "⁠Electrician",
  "⁠Engineer",
  "⁠Fashion Designer",
  "⁠Financial Analyst",
  "⁠Firefighter",
  "⁠Flight Attendant",
  "⁠Graphic Designer",
  "⁠Historian",
  "⁠Journalist",
  "⁠Judge",
  "⁠Lawyer",
  "⁠Librarian",
  "⁠Linguist",
  "⁠Marketing Manager",
  "⁠Mechanic",
  "⁠Musician",
  "⁠Nurse",
  "⁠Nutritionist",
  "⁠Optometrist",
  "⁠Painter",
  "⁠Paramedic",
  "⁠Pharmacist",
  "⁠Photographer",
  "⁠Physicist",
  "⁠Pilot",
  "⁠Police Officer",
  "⁠Politician",
  "⁠Professor",
  "⁠Psychologist",
  "⁠Real Estate Agent",
  "⁠Receptionist",
  "⁠Research Scientist",
  "⁠Salesperson",
  "⁠Scientist",
  "⁠Secretary",
  "⁠Social Worker",
  "⁠Software Developer",
  "⁠Surgeon",
  "⁠Teacher",
  "⁠Technician",
  "⁠Therapist",
  "⁠Translator",
  "⁠Truck Driver",
  "⁠Veterinarian",
  "⁠Waiter/Waitress",
  "⁠Web Developer",
  "⁠Writer",
  "⁠Account Manager",
  "⁠Acupuncturist",
  "⁠Administrative Assistant",
  "⁠Aerospace Engineer",
  "⁠Agricultural Scientist",
  "⁠Air Traffic Controller",
  "⁠Aircraft Mechanic",
  "⁠Animator",
  "⁠Appraiser",
  "⁠Archaeologist",
  "⁠Architectural Engineer",
  "⁠Art Director",
  "⁠Astronaut",
  "⁠Audiologist",
  "⁠Automotive Technician",
  "⁠Bank Teller",
  "⁠Barista",
  "⁠Bartender",
  "⁠Biochemist",
  "⁠Biomedical Engineer",
  "⁠Botanist",
  "⁠Building Inspector",
  "⁠Bus Driver",
  "⁠Cardiologist",
  "⁠Cartographer",
  "⁠Chaplain",
  "⁠Chauffeur",
  "⁠Chemist",
  "⁠Childcare Worker",
  "⁠Chiropractor",
  "⁠Civil Rights Lawyer",
  "⁠Claims Adjuster",
  "⁠Clergy",
  "⁠Coach",
  "Comedian",
];
export default categories;
